name: Android CI

on:
  push:
    branches:
      - main
    paths:
      - 'shared/**'
      - 'androidApp/**'
      - 'desktopApp/**'
      - 'iosApp/**'

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: 1SecMail-app-apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 1SecMail-app-apk
          asset_name: 1SecMail App
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release for 1SecMail App-1.0.0.apk"
