name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Desktop App (Mac os)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build DMG
        run: ./gradlew packageDmg

      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: 1SecMail-app.dmg
          path: desktopApp/build/compose/binaries/main/dmg/1SecMail App-1.0.0.dmg