name: Desktop Mac CI

on:
  push:
    branches:
      - main
    paths:
      - 'shared/**'
      - 'desktopApp/**'

jobs:
  build:
    name: Build Desktop App (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Window
        run: ./gradlew packageMsi

      - name: Upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: 1SecMail-app-msi
          path: desktopApp/build/compose/binaries/main/msi/1SecMail App-1.0.0.msi